### ISSUE TITLE
Changing the rend to style

### ISSUE THREAD

**Issue by geordee** [TEI-Boilerplate/TEI-Boilerplate#14]
Probably, it is better to leave the rend as rend itself, not changing it to style. We can render those using CSS attribute selectors.

For example:

``` css
    hi[rend=bold] {
      font-weight: bold;
    }
```
